### ISSUE TITLE
update nickname and update password

### ISSUE THREAD

**Issue by Lorakus** [Luis-Hebendanz/tagify-backend#35]
update nickname and update password needs fix

it should be like this :arrow_down: 

update nickname (PUT): 
> /api/user/me

json in body:
> {
> 	"nickname": "abc"
> }
> 

update password (PUT):

> /api/user/me/password

json in body:

> {
> 	"password": "password"
> }

**Comment by Marii19** [comment]
ready steady go

**Comment by Marii19** [comment]
pls close :)
